[package]
name = "fuzz-rustc-ast"
version = "0.1.0"
edition = "2021"

[dependencies]
arbitrary = "1.1.0"
# fork of syn with the arbitrary trait impls
syn = { git = "https://github.com/Nilstrieb/syn", branch = "arbitrary", features = ["full", "arbitrary"] }

[features]
